### ISSUE TITLE
shadowsocks 协议 只在第一次建立连接时 进行解密码？

### ISSUE THREAD

**Issue by jiatongwu** [loveinsky100/panama#11]
你好 你有没有博客或者个人网站，想跟你学习一下。 

@Override
    public void doProxy(byte []data) {
        String target = null;
        int port = 0;

        log.info("client ---------------->  proxy " + data.length + " byte");
        byte []decryptData = wrapper.unwrap(data);
        // 分包后第二个包不再去解析，直接复用先前的连接  
        if (null == redirectClient) {
            ShadowSocksRequest shadowSocksRequest = requestResolver.parse(decryptData);

            if (shadowSocksRequest.getAtyp() == ShadowSocksRequest.Type.UNKNOWN) {
                throw new RuntimeException("unknown request type: " + decryptData[0]);
            }

            target = shadowSocksRequest.getHost();
            port = shadowSocksRequest.getPort();

            if (shadowSocksRequest.getChannel() == ShadowSocksRequest.Channel.TCP) {
                int dataLength = shadowSocksRequest.getSubsequentDataLength();
                if (dataLength > 0) {
                    decryptData = Arrays.copyOfRange(decryptData, decryptData.length - dataLength, decryptData.length);
                }

            } else if (shadowSocksRequest.getChannel() == ShadowSocksRequest.Channel.UDP) {
                throw new RuntimeException("unsupport request type: udp");
            }
        }

        sendRequest2Target(decryptData, target, port);
    }

**Comment by jiatongwu** [comment]
shadowsocks 协议 有相关文档吗？

**Comment by loveinsky100** [comment]
协议百度上有很多介绍，分包的每个包都会解密，但第一个包会解析出目标的ip和端口，之后其余的包直接转发过去。

发自我的iPhone


------------------ 原始邮件 ------------------
From: jiatongwu ***@***.***&gt;
发送时间: 05/23/2021, 17:01
To: loveinsky100/panama ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
Subject: Reply:[loveinsky100/panama] shadowsocks 协议 只在第一次建立连接时 进行解密码？ (#11)





 
shadowsocks 协议 有相关文档吗？

**Comment by jiatongwu** [comment]
明白了  unwrap是解密

**Comment by jiatongwu** [comment]
https://wbuntu.com/p/676/ 这里有文档
https://www.ichenxiaoyu.com/ss/
