### ISSUE TITLE
shadowsocks粘包 拆包如何 处理？

### ISSUE THREAD

**Issue by jiatongwu** [loveinsky100/panama#12]
shadowsocks粘包 拆包如何 处理？
目前我看到的是通过channelReadComplete进行处理的 。
tcp socket 是没有边界的，需要自定义协议处理相邻2个包的边界。
shadowsocks协议 每个包的大小是多少，如何区分边界？

 @Override
    public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
        if (null == request) {
            request = new TCPRequest(ctx);
        }

        byte []readData = read(ctx, msg);
        if (null == data || data.length == 0) {
            data = readData;
        } else {
            int start = data.length;
            data = Arrays.copyOf(data, start + readData.length);
            System.arraycopy(readData, 0, data, start, readData.length);
        }

//        super.channelRead(ctx, msg);
    }

    @Override
    public void channelReadComplete(ChannelHandlerContext ctx) throws Exception {
        if (null == data || null == request) {
            super.channelReadComplete(ctx);
            return;
        }

        request.setData(data);
        doRequest(request);

        request = null;
        data = null;

        super.channelReadComplete(ctx);
    }

**Comment by jiatongwu** [comment]
我阅读了其他项目的源码 发现也没有进行拆包粘包的处理   对此不太理解  难道shadowsocks不需要处理粘包的情况？
例如 https://github.com/Saseke/zeus
public class Socks5CipherHandler extends MessageToMessageDecoder<ByteBuf> {

	private final InternalLogger logger = InternalLoggerFactory.getInstance(Socks5CipherInit.class);

	@Override
	protected void decode(ChannelHandlerContext ctx, ByteBuf msg, List<Object> out) {
		System.out.println("对数据进行了解密");
		AbstractCipher cipher = ctx.channel().attr(Socks5ServerConstant.SERVER_CIPHER).get();
		if (cipher == null) {
			ctx.close();
			logger.error("not found cipher method");
			return;
		}
		byte[] bytes = cipher.decodeBytes(msg);
		msg.clear().writeBytes(bytes);
		if (ctx.channel().attr(Socks5ServerConstant.DST_ADDRESS).get() == null) {
			SocketAddress clientAddress = ctx.channel().remoteAddress();
			InetSocketAddress inetSocketAddress = ShadowsocksUtils.getIp(msg);
			if (inetSocketAddress == null) {
				ctx.channel().close();
				logger.error("destination IP address not found");
				return;
			}
			ctx.channel().attr(Socks5ServerConstant.DST_ADDRESS).set(inetSocketAddress);
			logger.info("client ip:[{}] requests server [{}:{}]", clientAddress, inetSocketAddress.getAddress(),
					inetSocketAddress.getPort());
		}
		out.add(msg.retain());
	}

	@Override
	public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
		ctx.close();
		logger.error("a serious error occurred");
	}

}

**Comment by jiatongwu** [comment]
我看了下这个项目的zeus-client 源码  大概了解到 其实是对socks5的数据进行了包装 加密然后再发给shadowsocks server
但是为什么不需要 做粘包的处理呢？
  https://github.com/Saseke/zeus

**Comment by loveinsky100** [comment]
只需要原封不动的发给目标就行，目前服务器会自行处理。留个邮箱线下聊？

**Comment by jiatongwu** [comment]
> 只需要原封不动的发给目标就行，目前服务器会自行处理。留个邮箱线下聊？

jiatong.wu008@gmail.com

**Comment by jiatongwu** [comment]
在我阅读了https://github.com/xtuhcy/socks5-netty.git 这里的源码后 ，我知道原因了
是不需要做拆包粘包处理的
  socks5在success后就不关心具体的上层协议内容了 只做数据的转发
也就是说shadowsocks协议只要接收到第一个完整的包 获取到目标的ip port 后，和远端建立连接后 ，也不需要拆包粘包了，只做数据的转发。

仔细 看Socks5CommandRequestDecoder的源码 你会发现 当是success时 直接发送收到的byte数组，不需要做应用层协议的 拆包粘包  socks5在success后就不关心具体的上层协议内容了 只做数据的转发
 @Override
    protected void decode(ChannelHandlerContext ctx, ByteBuf in, List<Object> out) throws Exception {
        try {
            switch (state()) {
            case INIT: {
                final byte version = in.readByte();
                if (version != SocksVersion.SOCKS5.byteValue()) {
                    throw new DecoderException(
                            "unsupported version: " + version + " (expected: " + SocksVersion.SOCKS5.byteValue() + ')');
                }

                final Socks5CommandType type = Socks5CommandType.valueOf(in.readByte());
                in.skipBytes(1); // RSV
                final Socks5AddressType dstAddrType = Socks5AddressType.valueOf(in.readByte());
                final String dstAddr = addressDecoder.decodeAddress(dstAddrType, in);
                final int dstPort = in.readUnsignedShort();

                out.add(new DefaultSocks5CommandRequest(type, dstAddrType, dstAddr, dstPort));
                checkpoint(State.SUCCESS);
            }
            case SUCCESS: {
                int readableBytes = actualReadableBytes();
                if (readableBytes > 0) {
                    out.add(in.readRetainedSlice(readableBytes));
                }
                break;
            }
            case FAILURE: {
                in.skipBytes(actualReadableBytes());
                break;
            }
            }
        } catch (Exception e) {
            fail(out, e);
        }
    }
