### ISSUE TITLE
运行mvn package遇错，怎么解决？

### ISSUE THREAD

**Issue by briteming** [loveinsky100/panama#7]
hi.

root@bwg-vps panama-by-loveinsky100]# mvn package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] panama
[INFO] core
[INFO] server
[INFO] client
[INFO] spring
[INFO] test
[INFO] vpn
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building panama 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building core 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.maven.apache.org/maven2/io/netty/netty-all/4.1.31.Final/netty-all-4.1.31.Final.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] panama ............................................ SUCCESS [0.002s]
[INFO] core .............................................. FAILURE [0.887s]
[INFO] server ............................................ SKIPPED
[INFO] client ............................................ SKIPPED
[INFO] spring ............................................ SKIPPED
[INFO] test .............................................. SKIPPED
[INFO] vpn ............................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.107s
[INFO] Finished at: Wed Apr 15 16:54:27 CST 2020
[INFO] Final Memory: 7M/34M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project core: Could not resolve dependencies for project org.leo.server:core:jar:1.0-SNAPSHOT: Failed to collect dependencies at io.netty:netty-all:jar:4.1.31.Final: Failed to read artifact descriptor for io.netty:netty-all:jar:4.1.31.Final: Could not transfer artifact io.netty:netty-all:pom:4.1.31.Final from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/io/netty/netty-all/4.1.31.Final/netty-all-4.1.31.Final.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :core
[root@bwg-vps panama-by-loveinsky100]#

**Comment by briteming** [comment]
[root@bwg-vps brite]# java -version
openjdk version "11.0.3" 2019-04-16 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.3+7-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.3+7-LTS, mixed mode, sharing)
[root@bwg-vps brite]# 

不会跟我的java环境有关吧？

**Comment by loveinsky100** [comment]
你换成java8试下，还有看报错是http拉取netty时报错导致没有拉取到netty，如果你要用的话可以直接到release页面下载打包好的jar文件（ https://github.com/loveinsky100/panama/releases ）

**Comment by loveinsky100** [comment]
> [root@bwg-vps brite]# java -version
> openjdk version "11.0.3" 2019-04-16 LTS
> OpenJDK Runtime Environment 18.9 (build 11.0.3+7-LTS)
> OpenJDK 64-Bit Server VM 18.9 (build 11.0.3+7-LTS, mixed mode, sharing)
> [root@bwg-vps brite]#
> 
> 不会跟我的java环境有关吧？

Apache Maven 3.0.5 (Red Hat 3.0.5-17)
Maven home: /usr/share/maven
Java version: 1.8.0_242, vendor: Oracle Corporation

![image](https://user-images.githubusercontent.com/18205561/79356093-1c3ccc80-7f71-11ea-876a-5a042f3a16ec.png)

**Comment by luckypoem** [comment]
真是见鬼。我买了一个新vps,centos 8.
运行yum install -y java-1.8.0-openjdk java-1.8.0-openjdk-devel来安装jdk.
还是遇到类似的错误，我运行的mvn是3.1.1版。我在旧vps上，改为安装和运行mvn 3.0.5版，还是遇到类似错误，所以应该跟mvn的版本没多大关系。
可否告知你的gmail地址，我把vps的登陆细节发给你，你帮我看看。
非常感谢！

**Comment by loveinsky100** [comment]
> 真是见鬼。我买了一个新vps,centos 8.
> 运行yum install -y java-1.8.0-openjdk java-1.8.0-openjdk-devel来安装jdk.
> 还是遇到类似的错误，我运行的mvn是3.1.1版。我在旧vps上，改为安装和运行mvn 3.0.5版，还是遇到类似错误，所以应该跟mvn的版本没多大关系。
> 可否告知你的gmail地址，我把vps的登陆细节发给你，你帮我看看。
> 非常感谢！

xuyangze@gmail.com

**Comment by luckypoem** [comment]
@loveinsky100 
已发你邮箱

**Comment by loveinsky100** [comment]
> @loveinsky100
> 已发你邮箱

收到，已解决，请查收下邮件

**Comment by luckypoem** [comment]
yum install -y maven*或者apt-get install -y maven*即可解决问题。罪魁祸首就是maven没安装好。
还是用包管理器进行安装更可靠。
