### ISSUE TITLE
如何在mac上运行你这个程序？

### ISSUE THREAD

**Issue by briteming** [loveinsky100/panama#8]
hi.
我在mac上也装了你这个程序。
不过panama要是作为mac上的ss客户端，该怎么运行呢？

**Comment by loveinsky100** [comment]
> hi.
> 我在mac上也装了你这个程序。
> 不过panama要是作为mac上的ss客户端，该怎么运行呢？

这个是服务端，并非客户端，mac客户端可以去这里下载
https://github.com/shadowsocks/ShadowsocksX-NG/releases
